### ISSUE TITLE
ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: "Frameworks/NewRelic.framework/PrivacyInfo.xcprivacy"

### ISSUE THREAD

**Issue by panchal-krunal** [newrelic/newrelic-react-native-agent#160]
Hi All,
I have integrated NewRelic with my React Native app, it works fine, but on AppStore submission it gave below error -

Hello,

We noticed one or more issues with a recent submission for App Store review for the following app:

Neuroglee Health
Version 2.3.4
Build 10
Please correct the following issues and upload a new binary to App Store Connect.

ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: "Frameworks/NewRelic.framework/PrivacyInfo.xcprivacy". Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

Apple Developer Relations

I am using `newrelic-react-native-agent@1.3.3`

**Comment by shivam-aditya** [comment]
I am facing the same issue. 
I am using newrelic-react-native-agent (1.3.1) which internally uses the iOS NewRelicAgent (= 7.4.6)

**Comment by shivam-aditya** [comment]
The issue is even being seen for devs who have updated to the latest version 1.3.7. 
Link for reference - https://github.com/newrelic/newrelic-react-native-agent/issues/153#issuecomment-2070833778

**Comment by joseAlvarezTenpo** [comment]
Please correct the following issues and upload a new binary to App Store Connect.

ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/NewRelic.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by joseAlvarezTenpo** [comment]
@ndesai-newrelic please help us

**Comment by ndesai-newrelic** [comment]
@joseAlvarezTenpo we are looking into it, is this blocking you upload your app into appstore?

**Comment by joseAlvarezTenpo** [comment]
> @joseAlvarezTenpo we are looking into it, is this blocking you upload your app into appstore?

yes! we are blocked in the appstore

**Comment by joseAlvarezTenpo** [comment]
@ndesai-newrelic 

<img width="753" alt="Screenshot 2024-05-06 at 1 24 38 PM" src="https://github.com/newrelic/newrelic-react-native-agent/assets/128195682/bce599f0-bbfc-48da-9402-cc5ea3bfdc21">

**Comment by ndesai-newrelic** [comment]
@joseAlvarezTenpo  @shivam-aditya @panchal-krunal  It appears that the issue you're facing is a known problem within the React Native framework itself. Fortunately, the React Native team has addressed and resolved this issue in version 0.74.1 of their framework. To resolve the problem you're experiencing, you will need to update your React Native project to version 0.74.1 or later.
Once you've updated your project to the latest version of React Native, the issue should be resolved. However, if you continue to experience the same problem after upgrading, please let us know, and we'll further investigate and provide additional assistance.  

 https://github.com/facebook/react-native/commit/4be1fafec8edca5da5ebe515ad359d4178db7d23.   
  
https://github.com/react-native-community/discussions-and-proposals/discussions/776#discussioncomment-9216827

**Comment by joseAlvarezTenpo** [comment]
thanks @ndesai-newrelic. I working in the update to react-native, I will back with news when i finish that.

**Comment by ndesai-newrelic** [comment]
@joseAlvarezTenpo any update?

**Comment by joseAlvarezTenpo** [comment]
@ndesai-newrelic today o tomorrow i will finish the update.... we have change from 0.72.4 to 0.73.8

**Comment by joseAlvarezTenpo** [comment]
@ndesai-newrelic Did you test the library in the latest version of react native (0.74.1)?

**Comment by panchal-krunal** [comment]
@ndesai-newrelic After upgrading to the latest version of React Native (0.74.1) and latest version of newrelic-react-native-agent, the Android release app started crashing, here are the logs -
```
FATAL EXCEPTION: main
Process: com.xxx.yyy, PID: 4607
java.lang.ExceptionInInitializerError
	at com.newrelic.agent.android.tracing.TraceMachine.<init>(Unknown Source:3)
	at com.newrelic.agent.android.tracing.TraceMachine.d0(SourceFile:1)
	at com.newrelic.agent.android.tracing.TraceMachine.c0(SourceFile:1)
	at com.newrelic.agent.android.tracing.TraceMachine.b0(SourceFile:1)
	at com.facebook.react.p.onCreate(Unknown Source:4)
	at android.app.Activity.performCreate(Activity.java:8595)
	at android.app.Activity.performCreate(Activity.java:8573)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.RuntimeException: Missing type parameter.
	at w8.a.d(SourceFile:1)
	at w8.a.<init>(SourceFile:1)
	at com.newrelic.agent.android.harvest.type.a$a.<init>(Unknown Source:0)
	at com.newrelic.agent.android.harvest.type.a.<clinit>(Unknown Source:2)
	at com.newrelic.agent.android.tracing.TraceMachine.<init>(Unknown Source:3) 
	at com.newrelic.agent.android.tracing.TraceMachine.d0(SourceFile:1) 
	at com.newrelic.agent.android.tracing.TraceMachine.c0(SourceFile:1) 
	at com.newrelic.agent.android.tracing.TraceMachine.b0(SourceFile:1) 
	at com.facebook.react.p.onCreate(Unknown Source:4) 
	at android.app.Activity.performCreate(Activity.java:8595) 
	at android.app.Activity.performCreate(Activity.java:8573) 
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456) 
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764) 
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:205) 
	at android.os.Looper.loop(Looper.java:294) 
	at android.app.ActivityThread.main(ActivityThread.java:8177) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
```

**Comment by ndesai-newrelic** [comment]
@panchal-krunal  is ios issue resolved? can you open new issue for this crash and if possible please provide sample app as we are unable to reproduce this issue?

**Comment by panchal-krunal** [comment]
@ndesai-newrelic Upgrading RN app to 0.74.1 resolved iOS issue, I've submitted the app and Apple have accepted it.
Thanks a lot for the help. I will check with Android again, and will raise a new issue if it persists.
