### ISSUE TITLE
 java.lang.RuntimeException: Missing type parameter at com.newrelic.agent.android.harvest.type.a$a.<init>(Unknown Source:0)

### ISSUE THREAD

**Issue by panchal-krunal** [newrelic/newrelic-react-native-agent#161]
@ndesai-newrelic 
After upgrading to RN `0.74.1` and add `newrelic-react-native-agent`, started getting run time crash issue on Android
Steps configured -
 - Added `newrelic-react-native-agent@1.3.7`
 - Added `apply plugin: 'newrelic'` in `app/build.gradle`
 - Added `classpath "com.newrelic.agent.android:agent-gradle-plugin:7.3.0"` in `android/build.gradle`
 - Synced gradle from Android Studio
 - Build Release APK
 - Checked on Emulator
 - Crash
Error - 
```
FATAL EXCEPTION: Firebase Blocking Thread #0
Process: com.xxx.ttt.qa, PID: 9546
java.lang.ExceptionInInitializerError
at com.newrelic.agent.android.stats.a.A(SourceFile:1)
at com.newrelic.agent.android.stats.a.y(SourceFile:1)
at com.newrelic.agent.android.distributedtracing.TraceContext.j(SourceFile:1)
at com.newrelic.agent.android.instrumentation.h.g(SourceFile:1)
at com.newrelic.agent.android.instrumentation.e.<init>(Unknown Source:28)
at com.newrelic.agent.android.instrumentation.i.a(SourceFile:1)
at com.google.firebase.installations.remote.c.l(SourceFile:1)
at com.google.firebase.installations.remote.c.d(SourceFile:1)
at com.google.firebase.installations.c.A(SourceFile:1)
at com.google.firebase.installations.c.i(SourceFile:1)
at com.google.firebase.installations.c.u(SourceFile:1)
at com.google.firebase.installations.c.d(SourceFile:1)
at c7.d.run(SourceFile:1)
at com.google.firebase.concurrent.SequentialExecutor$a.run(Unknown Source:2)
at com.google.firebase.concurrent.SequentialExecutor$b.a(SourceFile:1)
at com.google.firebase.concurrent.SequentialExecutor$b.run(Unknown Source:0)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at com.google.firebase.concurrent.b.b(SourceFile:1)
at com.google.firebase.concurrent.b.a(SourceFile:1)
at com.google.firebase.concurrent.a.run(SourceFile:1)
at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.RuntimeException: Missing type parameter.
at w8.a.d(SourceFile:1)
at w8.a.<init>(SourceFile:1)
at com.newrelic.agent.android.harvest.type.a$a.<init>(Unknown Source:0)
at com.newrelic.agent.android.harvest.type.a.<clinit>(Unknown Source:2)
at com.newrelic.agent.android.stats.a.A(SourceFile:1) 
at com.newrelic.agent.android.stats.a.y(SourceFile:1) 
at com.newrelic.agent.android.distributedtracing.TraceContext.j(SourceFile:1) 
at com.newrelic.agent.android.instrumentation.h.g(SourceFile:1) 
at com.newrelic.agent.android.instrumentation.e.<init>(Unknown Source:28) 
at com.newrelic.agent.android.instrumentation.i.a(SourceFile:1) 
at com.google.firebase.installations.remote.c.l(SourceFile:1) 
at com.google.firebase.installations.remote.c.d(SourceFile:1) 
at com.google.firebase.installations.c.A(SourceFile:1) 
at com.google.firebase.installations.c.i(SourceFile:1) 
at com.google.firebase.installations.c.u(SourceFile:1) 
at com.google.firebase.installations.c.d(SourceFile:1) 
at c7.d.run(SourceFile:1) 
at com.google.firebase.concurrent.SequentialExecutor$a.run(Unknown Source:2) 
at com.google.firebase.concurrent.SequentialExecutor$b.a(SourceFile:1) 
at com.google.firebase.concurrent.SequentialExecutor$b.run(Unknown Source:0) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
at com.google.firebase.concurrent.b.b(SourceFile:1) 
at com.google.firebase.concurrent.b.a(SourceFile:1) 
at com.google.firebase.concurrent.a.run(SourceFile:1) 
at java.lang.Thread.run(Thread.java:1012) 
```

NOTE - Debug APK works fine though, the problem is only on release APK at runtime.

**Comment by ndesai-newrelic** [comment]
@panchal-krunal please check your proguard rules.

**Comment by panchal-krunal** [comment]
Thanks @ndesai-newrelic its working now.
