### ISSUE TITLE
Android Crash on opening - possible clash with Sentry/Microsoft clarity?

### ISSUE THREAD

**Issue by jamesmcn1** [newrelic/newrelic-react-native-agent#184]
Hi there we are getting a crash upon opening a release build of our React Native app (debug works fine).

We've followed the setup as instructed in the README.

## Steps to Reproduce

`build.gradle`
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24
        compileSdkVersion = 34
        targetSdkVersion = 34

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    subprojects { subproject ->
        afterEvaluate{
            if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
                android {
                    compileSdkVersion rootProject.ext.compileSdkVersion
                    buildToolsVersion rootProject.ext.buildToolsVersion
                }
            }
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath 'com.google.gms:google-services:4.3.15'
        classpath("io.sentry:sentry-android-gradle-plugin:3.14.0")
        classpath "com.newrelic.agent.android:agent-gradle-plugin:7.5.0"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

```

`app/build.gradle`

```
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

import com.android.build.OutputFile

/**
 * This is the configuration block to customize your React Native Android app.
 * By default you don't need to apply any configuration, just uncomment the lines you need.
 */

project.ext.sentryCli = [
    logLevel: "debug",
    flavorAware: true
]

react {
    /* Folders */
    //   The root of your project, i.e. where "package.json" lives. Default is '..'
    root = file("../../")
    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
    reactNativeDir = file("../../node_modules/react-native")
    //   The folder where the react-native Codegen package is. Default is ../node_modules/@react-native/codegen
    // codegenDir = file("../node_modules/@react-native/codegen")
    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
    cliFile = file("../../node_modules/react-native/cli.js")
}

apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
apply plugin: "io.sentry.android.gradle"

sentry {
    autoUploadProguardMapping = shouldSentryAutoUpload()
    uploadNativeSymbols = shouldSentryAutoUpload()
}

/**
 * Set this to true to Run Proguard on Release builds to minify the Java bytecode.
 */
def enableProguardInReleaseBuilds = true

def jscFlavor = 'org.webkit:android-jsc:+'

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        configurations.all {
            // https://github.com/facebook/flipper/issues/3397#issuecomment-1041597570
            resolutionStrategy { force 'androidx.sqlite:sqlite-framework:2.1.0' }
        }
    }
    buildTypes {
        debug {
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            shrinkResources = true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    flavorDimensions "environment"
    productFlavors {
        dev {
            dimension "environment"
            // Alternate google-services.json in matching folder
        }
        prod {
            dimension "environment"
            // Alternate google-services.json in matching folder
        }
    }

}

dependencies {
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")

    implementation "com.blueshift:android-sdk-x:3.3.1"

    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.google.firebase:firebase-messaging:23.1.1'

    implementation platform('com.google.firebase:firebase-bom:31.2.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation "com.google.firebase:firebase-installations"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'
apply plugin: 'newrelic'
```

## Expected Behavior

It should not crash, and send appropriate logs to NewRelic

## Relevant Logs / Console output

```
FATAL EXCEPTION: keychain-warming-up
                                                                                                    Process: com. .... .app, PID: 11033
                                                                                                    java.lang.StackOverflowError: stack size 1039KB
                                                                                                    	at java.util.Locale.equals(Locale.java:2467)
                                                                                                    	at libcore.icu.LocaleData.getCompatibleLocaleForBug159514442(LocaleData.java:165)
                                                                                                    	at java.util.Calendar.setWeekCountData(Calendar.java:3379)
                                                                                                    	at java.util.Calendar.<init>(Calendar.java:1612)
                                                                                                    	at java.util.GregorianCalendar.<init>(GregorianCalendar.java:627)
                                                                                                    	at java.util.Calendar.createCalendar(Calendar.java:1684)
                                                                                                    	at java.util.Calendar.getInstance(Calendar.java:1639)
                                                                                                    	at com.microsoft.clarity.rj.f.c(DateUtils.java:3)
                                                                                                    	at io.sentry.d.<init>(Breadcrumb.java:14)
                                                                                                    	at com.microsoft.clarity.sj.g0.b(SentryLogcatAdapter.java:3)
                                                                                                    	at com.microsoft.clarity.sj.g0.e(SentryLogcatAdapter.java:3)
                                                                                                    	at com.microsoft.clarity.pf.h.e(LogInstrumentation.java:1)
                                                                                                    	at com.microsoft.clarity.sj.g0.e(SentryLogcatAdapter.java:6)
                                                                                                    	at com.microsoft.clarity.pf.h.e(LogInstrumentation.java:1)
                                                                                                    	at com.microsoft.clarity.sj.g0.e(SentryLogcatAdapter.java:6)
                                                                                                    	at com.microsoft.clarity.pf.h.e(LogInstrumentation.java:1)
                                                                                                    	at com.microsoft.clarity.sj.g0.e(SentryLogcatAdapter.java:6)
                                                                                                    	at com.microsoft.clarity.pf.h.e(LogInstrumentation.java:1)
                                                                                                    	at com.microsoft.clarity.sj.g0.e(SentryLogcatAdapter.java:6)
                                                                                                    	at com.microsoft.clarity.pf.h.e(LogInstrumentation.java:1)
                                                                                                    	at com.microsoft.clarity.sj.g0.e(SentryLogcatAdapter.java:6)
                                                                                                    	at com.microsoft.clarity.pf.h.e(LogInstrumentation.java:1)
                                                                                                    	at com.microsoft.clarity.sj.g0.e(SentryLogcatAdapter.java:6)
                                                                                                    	...
                                                                                                    	at com.oblador.keychain.KeychainModule.internalWarmingBestCipher(KeychainModule.java:95)
                                                                                                    	at com.oblador.keychain.KeychainModule.a(KeychainModule.java:1)
                                                                                                    	at com.microsoft.clarity.yg.b.run(R8$$SyntheticClass:3)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

## Your Environment

`package.json`

```
    "@apollo/client": "^3.5.7",
    "@aws/dynamodb-auto-marshaller": "^0.7.1",
    "@contentful/rich-text-react-renderer": "^15.11.1",
    "@contentful/rich-text-types": "^15.11.1",
    "@gorhom/bottom-sheet": "^4.6.1",
    "@gorhom/portal": "^1.0.14",
    "@hapi/joi": "^17.1.1",
    "@optimizely/react-sdk": "^3.0.0",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-native-community/datetimepicker": "^6.4.2",
    "@react-native-community/netinfo": "^11.2.1",
    "@react-native-firebase/analytics": "^13.1.1",
    "@react-native-firebase/app": "^13.1.1",
    "@react-native-firebase/remote-config": "^13.1.1",
    "@react-native-masked-view/masked-view": "0.2.9",
    "@react-native-picker/picker": "^2.4.8",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.2.0",
    "@reduxjs/toolkit": "^1.6.2",
    "@sentry/react-native": "5.14.1",
    "apollo3-cache-persist": "0.14.1",
    "blueshift-react-native": "^1.1.2",
    "crypto-js": "^4.1.1",
    "d3-time-format": "^4.1.0",
    "date-fns": "^2.30.0",
    "date-fns-tz": "^2.0.0",
    "graphql": "^15.5.1",
    "jail-monkey": "^2.6.0",
    "js-base64": "^3.6.1",
    "js-cookie": "^3.0.0",
    "jsbarcode": "^3.11.4",
    "jwt-decode": "^3.1.2",
    "lodash.orderby": "^4.6.0",
    "lodash.sortby": "^4.7.0",
    "lottie-react-native": "^5.1.6",
    "moment": "^2.29.1",
    "newrelic-react-native-agent": "1.4.1",
    "react": "^18.2.0",
    "react-error-boundary": "^3.1.4",
    "react-native": "^0.72",
    "react-native-blob-util": "^0.18.2",
    "react-native-clarity": "^2.0.0",
    "react-native-click-outside": "^0.1.1",
    "react-native-code-push": "^8.0.2",
    "react-native-config": "^1.5.1",
    "react-native-device-info": "^8.7.1",
    "react-native-dotenv": "^2.5.5",
    "react-native-dropdown-picker": "patch:react-native-dropdown-picker@5.1.23#patches/react-native-dropdown-picker.patch",
    "react-native-gesture-handler": "2.12.0",
    "react-native-get-random-values": "^1.9.0",
    "react-native-gifted-charts": "1.3.11",
    "react-native-haptic-feedback": "^2.2.0",
    "react-native-hide-with-keyboard": "^1.2.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-keychain": "^8.1.1",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-mask-input": "^1.2.3",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^15.0.1",
    "react-native-pager-view": "patch:react-native-pager-view@5.0.12#patches/react-native-pager-view.patch",
    "react-native-picker-select": "^8.0.4",
    "react-native-rate": "^1.2.9",
    "react-native-reanimated": "^3.5.4",
    "react-native-recaptcha-that-works": "^1.3.2",
    "react-native-root-toast": "^3.4.1",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.25.0",
    "react-native-select-dropdown": "^3.3.4",
    "react-native-size-matters": "^0.4.0",
    "react-native-snap-carousel": "4.0.0-beta.6",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^13.9.0",
    "react-native-text-input-mask": "latest",
    "react-native-torch": "^1.2.0",
    "react-native-uuid": "^2.0.1",
    "react-native-webview": "^11.26.1",
    "react-native-worldpay": "workspace:packages/worldpay",
    "react-native-youtube-iframe": "^2.2.2",
    "react-redux": "^7.2.2",
    "redux": "^4.1.1",
    "redux-flipper": "^2.0.3",
    "redux-mock-store": "^1.5.4",
    "redux-persist": "^6.0.0",
    "text-encoding-polyfill": "^0.6.7",
    "validate.js": "^0.13.1",
    "victory-native": "36.6.11"
   ```

`gradle-wrapper.properties`

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip
networkTimeout=10000
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by ndesai-newrelic** [comment]
@jamesmcn1 we'll take care of this on our end. Just to clarify, both Sentry and New Relic are currently performing log instrumentation for your system. To optimize your monitoring process, it would be advisable to choose and use only one of these services.

**Comment by jamesmcn1** [comment]
Thanks @ndesai-newrelic! yes, we're aware they are similar but our stakeholders would want the functionality from both, in an ideal world. 

So this is something you can fix in a future release?

**Comment by ndesai-newrelic** [comment]
@jamesmcn1 I will check it from our side.

**Comment by ndesai-newrelic** [comment]
@jamesmcn1  this can be easily fixed just adding this on your app level build.gradle file.


**newrelic {
    // Don't instrument sample classes
    excludePackageInstrumentation("io.sentry.*")
}**

**Comment by appinDhaval** [comment]
we have put below code at top in our app level build.gradle

`apply plugin: 'newrelic'`

how can we solve this crash, can you help us on this?

**Comment by DarshanSavaliyaGitHub** [comment]
Please put this code in your `proguard-rules.pro`

> -keep class com.newrelic.** { *; }
-dontwarn com.newrelic.**
-keepattributes Exceptions, Signature, InnerClasses, LineNumberTable, SourceFile, EnclosingMethod
-keepattributes Signature
-keep class [com.newrelic.com](http://com.newrelic.com/).google.gson.reflect.TypeToken { *; }
-keep class * extends [com.newrelic.com](http://com.newrelic.com/).google.gson.reflect.TypeToken
-keepattributes *Annotation*

**Comment by jamesmcn1** [comment]
Thanks both! adding the below has fixed the crash and we're now getting logs from New Relic in Android builds 👍 

`app/build.gradle`

```
apply plugin: 'newrelic'

newrelic {
    // Don't instrument sample classes
    excludePackageInstrumentation("io.sentry.*")
}
```

To proguard rules:

```
# New Relic
-keep class com.newrelic.** { *; }
-dontwarn com.newrelic.*
-keepattributes Exceptions, Signature, InnerClasses, LineNumberTable, SourceFile, EnclosingMethod
-keepattributes Signature
-keep class com.newrelic.com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.newrelic.com.google.gson.reflect.TypeToken
-keepattributes Annotation
```
